### DISCUSSION TITLE
Need help getting started with configs

### DISCUSSION THREAD

**Discussion by cltsang** [grblHAL/core#105] [Q&A] [answered]
Greetings.
Recently I discover this project, and want to switch over from FluidNC, mainly due to idf support and better code abstraction and organization.

I have been scratching my head for a few days,  trying to tweak `config.h` and `my_machine_map.h`, but still have yet to successfully move the motors. So may I have some guidance please?

My machine has no limit switches on X and Y axis, and one limit switch on the negative side of Z axis.
Both Z and shared enable switches are pulled up in the circuit, with `LOW` to enable and `HIGH` to disable.
Homing is irrelevant not needed. There are no control pins.

My FluidNC config.yaml to drive it is
```yaml
name: "MyCNC"
board: "MyCNC"

start:
  must_home: false

stepping:
  engine: RMT
  idle_ms: 254
  dir_delay_us: 1
  pulse_us: 3
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.19
  
  x:
    steps_per_mm: 34
    max_rate_mm_per_min: 2200
    acceleration_mm_per_sec2: 80
    max_travel_mm: 51
    
    motor0:
      standard_stepper:
        direction_pin: gpio.5
        step_pin: gpio.18
    motor1:
      null_motor:

  y:
    steps_per_mm: 34
    max_rate_mm_per_min: 2200
    acceleration_mm_per_sec2: 80
    max_travel_mm: 51

    motor0:
      standard_stepper:
        direction_pin: gpio.22
        step_pin: gpio.21
    motor1:
      null_motor:

  z:
    steps_per_mm: 50
    max_rate_mm_per_min: 700
    acceleration_mm_per_sec2: 100
    max_travel_mm: 15

    motor0:
      limit_neg: gpio.23
      hard_limits: false
      standard_stepper:
        direction_pin: gpio.4
        step_pin: gpio.16
        disable_pin: gpio.17
    motor1:
      null_motor:
```

My current incorrect settings for grblHAL is

`my_machine_map.h`
```c
static const int UNDEFINED_PIN = 255;

#define STEP_TIMER_GROUP TIMER_GROUP_0
#define STEP_TIMER_INDEX TIMER_0

#define X_STEP_PIN GPIO_NUM_18
#define Y_STEP_PIN GPIO_NUM_21
#define Z_STEP_PIN GPIO_NUM_16

#define X_DIRECTION_PIN GPIO_NUM_5
#define Y_DIRECTION_PIN GPIO_NUM_22
#define Z_DIRECTION_PIN GPIO_NUM_4

#define STEPPERS_ENABLE_PIN GPIO_NUM_19

#define X_LIMIT_PIN UNDEFINED_PIN
#define Y_LIMIT_PIN UNDEFINED_PIN
#define Z_LIMIT_PIN GPIO_NUM_23

#define SPINDLE_ENABLE_PIN UNDEFINED_PIN
#define SPINDLEPWMPIN UNDEFINED_PIN
```

`grbl/config.h`
```c
// only showing lines with my edits
#define INVERT_ST_ENABLE_MASK (X_AXIS_BIT|Y_AXIS_BIT)
#define INVERT_LIMIT_BIT_MASK (X_AXIS_BIT|Y_AXIS_BIT|Z_AXIS_BIT)

#define DEFAULT_X_STEPS_PER_MM 34.0f
#define DEFAULT_Y_STEPS_PER_MM DEFAULT_X_STEPS_PER_MM
#define DEFAULT_Z_STEPS_PER_MM 50.0f
#define DEFAULT_X_MAX_RATE 2200.0f
#define DEFAULT_Y_MAX_RATE DEFAULT_X_MAX_RATE
#define DEFAULT_Z_MAX_RATE 700.0f
#define DEFAULT_X_ACCELERATION 80
#define DEFAULT_Y_ACCELERATION DEFAULT_X_ACCELERATION
#define DEFAULT_Z_ACCELERATION 100
#define DEFAULT_X_MAX_TRAVEL 51.0f
#define DEFAULT_Y_MAX_TRAVEL DEFAULT_X_MAX_TRAVEL
#define DEFAULT_Z_MAX_TRAVEL 15.0f

#define DEFAULT_STEP_PULSE_MICROSECONDS 3.0f
#define DEFAULT_STEPPER_IDLE_LOCK_TIME 254
#define DEFAULT_JUNCTION_DEVIATION 0.01f
#define DEFAULT_ARC_TOLERANCE 0.002f
```

Can you point out what I'm doing incorrectly here please?
Thank you.
